// 

namespace AutoHitCounter.Enums;

public enum AsmScript
{
    DSRHit,
    DSRApplyHealthDelta,
    DSRKillChr,
    DSRCheckAuxAttacker,
    DSRAuxProc,
    DSREventLog,
    DSRClearThrowState,
    DSRSetThrowState,
    DSRRunStart,
    
    VanillaCheckPlayerDead,
    VanillaHit,
    VanillaCountAuxHit,
    VanillaGeneralApplyDamage,
    VanillaKillBox,
    VanillaHasIframes,
    VanillaClearWetPoisonBit,
    VanillaStaggerCheck,
    VanillaEventLog,
    VanillaIgtNewGame,
    VanillaIgtStop,
    VanillaIgtLoadGame,
    VanillaBabyJump,
    VanillaCreditSkip,
    
    ScholarHit,
    ScholarGeneralApplyDamage,
    ScholarKillBox,
    ScholarCountAuxHit,
    ScholarHasIframes,
    ScholarClearWetPoisonBit,
    ScholarStaggerCheck,
    ScholarEventLog,
    ScholarIgtNewGame,
    ScholarIgtStop,
    ScholarIgtLoadGame,
    ScholarCheckPlayerDead,
    ScholarBabyJump,
    ScholarCreditSkip,
    
    DS3CheckPlayerDead,
    DS3Hit,
    DS3CheckAuxAttacker,
    DS3AuxProc,
    DS3GetSpEffect,
    DS3JailerDrain,
    DS3ApplyHealthDelta,
    DS3KillBox,
    DS3CheckStaggerIgnore,
    DS3EventLog,
    DS3StoreFallHeight,
    DS3IsFallDamageDisabled,
    DS3SetThrowState,
    DS3ClearThrowState,
    DS3RunStart,
    DS3NoInvasions,
    
    
    SKCheckPlayerDead,
    SKHit,
    SKLethalFall,
    SKFadeFall,
    SKApplyHealthDelta,
    SKPostHit,
    SKStaggerIgnoreCheck,
    SKAuxProc,
    SKCheckAuxAttacker,
    SKHkbFireEvent,
    SKFadeFallHeight,
    SKDeferredFallCheck,
    SKApplySpEffectDamage,
    SKSakuraDance,
    SKEventLog,
    SKRunStart,
    SKBossHealthBarLog,

    EldenRingHit,
    EldenRingCheckPlayerDead,
    EldenRingFallDamage,
    EldenRingKillBox,
    EldenRingAuxDamageAttacker,
    EldenRingAuxProc,
    EldenRingSpEffectTickDamage,
    EldenRingStaggerEndure,
    EldenRingEnvKilling,
    EldenRingCheckStateInfo,
    EldenRingDeflectTear,
    EldenRingKillChr,
    EldenRingHandleThrow,
    EldenRingClearThrowState,
    EldenRingEventLog,
    EldenRingRunStart,
}