//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoHitCounter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoHitCounter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BossName,DeathFlag
        ///The Last Giant,100971
        ///The Pursuer,100968
        ///Dragonrider,100959
        ///Old Dragonslayer,100960
        ///Flexile Sentry,100961
        ///Ruin Sentinels,100962
        ///The Lost Sinner,100963
        ///Belfry Gargoyles,101001
        ///Executioner&apos;s Chariot,100953
        ///Skeleton Lords,100954
        ///Covetous Demon,100955
        ///&quot;Mytha, the Baneful Queen&quot;,100956
        ///Red Smelter Demon,100964
        ///Old Iron King,100952
        ///Scorpioness Najka,100957
        ///Royal Rat Authority,100967
        ///Prowling Magus &amp; Congregation,101000
        ///The Duke&apos;s Dear Freja,100951
        ///Royal Rat Vanguard,100965
        ///T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS2Events {
            get {
                return ResourceManager.GetString("DS2Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 7 &lt;_main+0x7&gt;
        ///74 69                   je     72 &lt;skip_all&gt;
        ///50                      push   rax
        ///e8 00 00 00 00          call   f &lt;_main+0xf&gt;
        ///74 60                   je     71 &lt;skip&gt;
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 18 &lt;_main+0x18&gt;
        ///48 85 c0                test   rax,rax
        ///74 54                   je     71 &lt;skip&gt;
        ///48 8b 80 80 00 00 00    mov    rax,QWORD PTR [rax+0x80]
        ///48 85 c0                test   rax,rax
        ///74 4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3ApplyHealthDelta {
            get {
                return ResourceManager.GetString("DS3ApplyHealthDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 09 42 4c             or     DWORD PTR [r10+0x4c],eax
        ///43 8b 4c 9a 24          mov    ecx,DWORD PTR [r10+r11*4+0x24]
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 10 &lt;_main+0x10&gt;
        ///74 06                   je     18 &lt;skip&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 18 &lt;skip&gt;
        ///
        ///000000000018 &lt;skip&gt;:
        ///e9 00 00 00 00          jmp    1d &lt;skip+0x5&gt;.
        /// </summary>
        internal static string DS3AuxProc {
            get {
                return ResourceManager.GetString("DS3AuxProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///e8 00 00 00 00          call   6 &lt;_main+0x6&gt;
        ///74 30                   je     38 &lt;skip&gt;
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # f &lt;_main+0xf&gt;
        ///48 3b 90 80 00 00 00    cmp    rdx,QWORD PTR [rax+0x80]
        ///75 20                   jne    38 &lt;skip&gt;
        ///4d 85 c0                test   r8,r8
        ///74 12                   je     2f &lt;set_check_proc_flag&gt;
        ///4c 3b 80 80 00 00 00    cmp    r8,QWORD PTR [rax+0x80]
        ///75 09                   jne    2f &lt;set_check_proc_flag&gt;
        ///41 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3CheckAuxAttacker {
            get {
                return ResourceManager.GetString("DS3CheckAuxAttacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 7 &lt;_main+0x7&gt;
        ///48 85 c0                test   rax,rax
        ///74 29                   je     35 &lt;dead&gt;
        ///48 8b 80 80 00 00 00    mov    rax,QWORD PTR [rax+0x80]
        ///48 85 c0                test   rax,rax
        ///74 1d                   je     35 &lt;dead&gt;
        ///48 8b 80 90 1f 00 00    mov    rax,QWORD PTR [rax+0x1f90]
        ///48 85 c0                test   rax,rax
        ///74 11                   je     35 &lt;dead&gt;
        ///48 8b 40 18             mov    rax,QWORD PTR [rax+0x18]
        ///48 85 c0       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3CheckPlayerDead {
            get {
                return ResourceManager.GetString("DS3CheckPlayerDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 7 &lt;_main+0x7&gt;
        ///74 11                   je     1a &lt;original&gt;
        ///85 c0                   test   eax,eax
        ///74 06                   je     13 &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 13 &lt;exit&gt;
        ///
        ///000000000013 &lt;exit&gt;:
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 1a &lt;original&gt;
        ///
        ///00000000001a &lt;original&gt;:
        ///45 0f 57 c0             xorps  xmm8,xmm8
        ///85 c0                   test   eax,eax
        ///e9 00 00 00 00          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3CheckStaggerIgnore {
            get {
                return ResourceManager.GetString("DS3CheckStaggerIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 29 74 24 40          movaps XMMWORD PTR [rsp+0x40],xmm6
        ///53                      push   rbx
        ///48 8b 1d 00 00 00 00    mov    rbx,QWORD PTR [rip+0x0]        # d &lt;_main+0xd&gt;
        ///48 85 db                test   rbx,rbx
        ///74 10                   je     22 &lt;exit&gt;
        ///48 3b 83 80 00 00 00    cmp    rax,QWORD PTR [rbx+0x80]
        ///75 07                   jne    22 &lt;exit&gt;
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 22 &lt;exit&gt;
        ///
        ///000000000022 &lt;exit&gt;:
        ///5b                      pop    rbx
        ///e9 00 00 00 00         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3ClearThrowState {
            get {
                return ResourceManager.GetString("DS3ClearThrowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///53                      push   rbx
        ///57                      push   rdi
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # 9 &lt;_main+0x9&gt;
        ///89 f8                   mov    eax,edi
        ///6b c0 05                imul   eax,eax,0x5
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # 15 &lt;_main+0x15&gt;
        ///48 01 c3                add    rbx,rax
        ///89 13                   mov    DWORD PTR [rbx],edx
        ///44 88 43 04             mov    BYTE PTR [rbx+0x4],r8b
        ///ff c7                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3EventLog {
            get {
                return ResourceManager.GetString("DS3EventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BossName,DeathFlag
        ///&quot;Aldrich, Devourer of Gods&quot;,50002130
        ///Abyss Watchers,13300800
        ///Ancient Wyvern,50002070
        ///Champion Gundyr,14000830
        ///Crystal Sage,13300850
        ///Curse-Rotted Greatwood,13100800
        ///Dancer of the Boreal Valley,13000890
        ///Darkeater Midir,50002350
        ///Deacons of the Deep,13500800
        ///Demon Prince,50002330
        ///Dragonslayer Armour,13010800
        ///Gravetender,6323
        ///Halflight,15100800
        ///High Lord Wolnir,50002140
        ///Iudex Gundyr,14000800
        ///Nameless King,13200850
        ///&quot;Oceiros, the Consumed King&quot;,13000830
        ///Old Demon King,50002150        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3Events {
            get {
                return ResourceManager.GetString("DS3Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 7 &lt;_main+0x7&gt;
        ///48 85 c0                test   rax,rax
        ///74 17                   je     23 &lt;null&gt;
        ///48 8b 80 80 00 00 00    mov    rax,QWORD PTR [rax+0x80]
        ///48 85 c0                test   rax,rax
        ///74 0b                   je     23 &lt;null&gt;
        ///48 8b 80 c8 11 00 00    mov    rax,QWORD PTR [rax+0x11c8]
        ///48 85 c0                test   rax,rax
        ///c3                      ret
        ///
        ///000000000023 &lt;null&gt;:
        ///31 c0                   xor    eax,eax
        ///c3                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3GetSpEffect {
            get {
                return ResourceManager.GetString("DS3GetSpEffect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 7 &lt;_main+0x7&gt;
        ///0f 84 dc 00 00 00       je     e9 &lt;skip_all&gt;
        ///50                      push   rax
        ///e8 00 00 00 00          call   13 &lt;_main+0x13&gt;
        ///58                      pop    rax
        ///0f 84 cf 00 00 00       je     e9 &lt;skip_all&gt;
        ///50                      push   rax
        ///57                      push   rdi
        ///52                      push   rdx
        ///53                      push   rbx
        ///48 89 d7                mov    rdi,rdx
        ///48 8b 15 00 00 00 00    mov    rdx,QWO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3Hit {
            get {
                return ResourceManager.GetString("DS3Hit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e8 00 00 00 00          call   5 &lt;_main+0x5&gt;
        ///50                      push   rax
        ///53                      push   rbx
        ///48 8b 1d 00 00 00 00    mov    rbx,QWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///48 85 db                test   rbx,rbx
        ///0f 84 b6 00 00 00       je     cd &lt;exit&gt;
        ///48 8b 9b 80 00 00 00    mov    rbx,QWORD PTR [rbx+0x80]
        ///48 85 db                test   rbx,rbx
        ///0f 84 a6 00 00 00       je     cd &lt;exit&gt;
        ///48 3b 5e 08             cmp    rbx,QWORD PTR [rsi+0x8]
        ///0f 85 9c 00 00 00       jne    cd &lt;exi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3IsFallDamageDisabled {
            get {
                return ResourceManager.GetString("DS3IsFallDamageDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 86 00 00 00 00       jbe    6 &lt;_main+0x6&gt;
        ///f3 0f 59 f0             mulss  xmm6,xmm0
        ///81 7b 60 83 2e 00 00    cmp    DWORD PTR [rbx+0x60],0x2e83
        ///75 40                   jne    53 &lt;skip&gt;
        ///50                      push   rax
        ///51                      push   rcx
        ///52                      push   rdx
        ///e8 00 00 00 00          call   1b &lt;_main+0x1b&gt;
        ///74 33                   je     50 &lt;exit&gt;
        ///48 39 f0                cmp    rax,rsi
        ///75 2e                   jne    50 &lt;exit&gt;
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3JailerDrain {
            get {
                return ResourceManager.GetString("DS3JailerDrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 cb                mov    rbx,rcx
        ///31 d2                   xor    edx,edx
        ///50                      push   rax
        ///e8 00 00 00 00          call   b &lt;_main+0xb&gt;
        ///58                      pop    rax
        ///74 18                   je     26 &lt;exit&gt;
        ///51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # 16 &lt;_main+0x16&gt;
        ///48 3b 81 80 00 00 00    cmp    rax,QWORD PTR [rcx+0x80]
        ///59                      pop    rcx
        ///75 06                   jne    26 &lt;exit&gt;
        ///ff 05 00 00 00 00    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3KillBox {
            get {
                return ResourceManager.GetString("DS3KillBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e8 00 00 00 00          call   5 &lt;_main+0x5&gt;
        ///53                      push   rbx
        ///48 8b 5c 24 70          mov    rbx,QWORD PTR [rsp+0x70]
        ///48 85 db                test   rbx,rbx
        ///74 07                   je     17 &lt;done&gt;
        ///80 3b 01                cmp    BYTE PTR [rbx],0x1
        ///75 02                   jne    17 &lt;done&gt;
        ///30 c0                   xor    al,al
        ///
        ///000000000017 &lt;done&gt;:
        ///5b                      pop    rbx
        ///e9 00 00 00 00          jmp    1d &lt;done+0x6&gt;.
        /// </summary>
        internal static string DS3NoInvasions {
            get {
                return ResourceManager.GetString("DS3NoInvasions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 b0 01                mov    r8b,0x1
        ///31 d2                   xor    edx,edx
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # c &lt;_main+0xc&gt;
        ///e9 00 00 00 00          jmp    11 &lt;_main+0x11&gt;.
        /// </summary>
        internal static string DS3RunStart {
            get {
                return ResourceManager.GetString("DS3RunStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 8b 11 02 00 00 20    or     BYTE PTR [rbx+0x211],0x20
        ///50                      push   rax
        ///e8 00 00 00 00          call   d &lt;_main+0xd&gt;
        ///74 34                   je     43 &lt;exit&gt;
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 16 &lt;_main+0x16&gt;
        ///48 85 c0                test   rax,rax
        ///74 28                   je     43 &lt;exit&gt;
        ///48 8b 80 80 00 00 00    mov    rax,QWORD PTR [rax+0x80]
        ///48 85 c0                test   rax,rax
        ///74 1c                   je     43 &lt;exit&gt;
        ///48 8b 80 90 1f 00 00    mov  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3SetThrowState {
            get {
                return ResourceManager.GetString("DS3SetThrowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 85 c0                test   rax,rax
        ///74 29                   je     36 &lt;skip&gt;
        ///48 8b 80 80 00 00 00    mov    rax,QWORD PTR [rax+0x80]
        ///48 85 c0                test   rax,rax
        ///74 1d                   je     36 &lt;skip&gt;
        ///48 39 07                cmp    QWORD PTR [rdi],rax
        ///75 18                   jne    36 &lt;skip&gt;
        ///f3 0f 11 35 00 00 00    movss  DWORD PTR [rip+0x0],xmm6        # 26 &lt;_main+0x26&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DS3StoreFallHeight {
            get {
                return ResourceManager.GetString("DS3StoreFallHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 7c 24 40          mov    QWORD PTR [rsp+0x40],rdi
        ///50                      push   rax
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///48 39 44 24 30          cmp    QWORD PTR [rsp+0x30],rax
        ///74 2b                   je     42 &lt;process&gt;
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 1e &lt;_main+0x1e&gt;
        ///74 11                   je     31 &lt;next&gt;
        ///48 b8 00 00 00 00 00    movabs rax,0x0
        ///00 00 00 
        ///48 39 44 24 30          cmp    QWORD PTR [rsp+0x30],rax
        ///74 11                   je     42 &lt;p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSRApplyHealthDelta {
            get {
                return ResourceManager.GetString("DSRApplyHealthDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44 8b 83 34 04 00 00    mov    r8d,DWORD PTR [rbx+0x434]
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # e &lt;_main+0xe&gt;
        ///74 2b                   je     3b &lt;early_exit&gt;
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 18 &lt;_main+0x18&gt;
        ///48 85 c0                test   rax,rax
        ///74 1d                   je     3a &lt;exit&gt;
        ///48 8b 40 68             mov    rax,QWORD PTR [rax+0x68]
        ///48 85 c0                test   rax,rax
        ///74 14                   je     3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSRAuxProc {
            get {
                return ResourceManager.GetString("DSRAuxProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 7 &lt;_main+0x7&gt;
        ///0f b6 80 56 01 00 00    movzx  eax,BYTE PTR [rax+0x156]
        ///48 83 7c 24 10 00       cmp    QWORD PTR [rsp+0x10],0x0
        ///74 3d                   je     53 &lt;early_exit&gt;
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 1e &lt;_main+0x1e&gt;
        ///48 85 c0                test   rax,rax
        ///74 2f                   je     52 &lt;exit&gt;
        ///48 8b 40 68             mov    rax,QWORD PTR [rax+0x68]
        ///48 85 c0         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSRCheckAuxAttacker {
            get {
                return ResourceManager.GetString("DSRCheckAuxAttacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 8b 48 04 00 00    mov    rcx,QWORD PTR [rbx+0x448]
        ///48 85 c9                test   rcx,rcx
        ///74 21                   je     2d &lt;exit&gt;
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 14 &lt;_main+0x14&gt;
        ///48 85 c0                test   rax,rax
        ///74 13                   je     2c &lt;pop_exit&gt;
        ///48 3b 58 68             cmp    rbx,QWORD PTR [rax+0x68]
        ///75 0d                   jne    2c &lt;pop_exit&gt;
        ///80 79 20 06             cmp    BYTE PTR [rcx+0x20],0x6
        ///74 07      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSRClearThrowState {
            get {
                return ResourceManager.GetString("DSRClearThrowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///53                      push   rbx
        ///57                      push   rdi
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # 9 &lt;_main+0x9&gt;
        ///89 f8                   mov    eax,edi
        ///6b c0 05                imul   eax,eax,0x5
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # 15 &lt;_main+0x15&gt;
        ///48 01 c3                add    rbx,rax
        ///89 13                   mov    DWORD PTR [rbx],edx
        ///44 88 43 04             mov    BYTE PTR [rbx+0x4],r8b
        ///ff c7                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSREventLog {
            get {
                return ResourceManager.GetString("DSREventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BossName,DeathFlag
        ///4 Kings,13
        ///Artorias,11215015
        ///Asylum Demon,16
        ///Bed of Chaos,10
        ///Bell Gargoyles,3
        ///Capra Demon,11015375
        ///Ceaseless Discharge,11410900
        ///Centipede Demon,11415384
        ///Chaos Witch Quelaag,9
        ///Demon Firesage,11415344
        ///Gaping Dragon,2
        ///Gwyndolin,11510900
        ///Gwyn,15
        ///Iron Golem,11
        ///Kalameet,11210004
        ///Manus,11215025
        ///Moonlight Butterfly,11200900
        ///Nito,7
        ///Ornstein &amp; Smough,12
        ///Pinwheel,6
        ///Priscilla,4
        ///Sanctuary Guardian,11215005
        ///Seath,14
        ///Sif,5
        ///Stray Demon,11810900
        ///Taurus Demon,11015385.
        /// </summary>
        internal static string DSREvents {
            get {
                return ResourceManager.GetString("DSREvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 7 &lt;_main+0x7&gt;
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # e &lt;_main+0xe&gt;
        ///0f 84 97 00 00 00       je     ab &lt;skip_all&gt;
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 1c &lt;_main+0x1c&gt;
        ///48 85 c0                test   rax,rax
        ///0f 84 85 00 00 00       je     aa &lt;exit&gt;
        ///48 8b 40 68             mov    rax,QWORD PTR [rax+0x68]
        ///48 85 c0                test   rax,rax
        ///74 7c          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSRHit {
            get {
                return ResourceManager.GetString("DSRHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8d 64 24 f8          lea    rsp,[rsp-0x8]
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # d &lt;_main+0xd&gt;
        ///48 85 c0                test   rax,rax
        ///74 0c                   je     1e &lt;exit&gt;
        ///48 3b 48 68             cmp    rcx,QWORD PTR [rax+0x68]
        ///75 06                   jne    1e &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 1e &lt;exit&gt;
        ///
        ///00000000001e &lt;exit&gt;:
        ///58                      pop    rax
        ///e9 00 00 00 00          jmp    24 &lt;exit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSRKillChr {
            get {
                return ResourceManager.GetString("DSRKillChr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b9 67 2b 00 00          mov    ecx,0x2b67
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # c &lt;_main+0xc&gt;
        ///e9 00 00 00 00          jmp    11 &lt;_main+0x11&gt;.
        /// </summary>
        internal static string DSRRunStart {
            get {
                return ResourceManager.GetString("DSRRunStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81 8b dc 01 00 00 00    or     DWORD PTR [rbx+0x1dc],0x200000
        ///00 20 00 
        ///50                      push   rax
        ///51                      push   rcx
        ///48 8b 43 10             mov    rax,QWORD PTR [rbx+0x10]
        ///48 85 c0                test   rax,rax
        ///74 39                   je     4e &lt;exit&gt;
        ///48 8b 40 10             mov    rax,QWORD PTR [rax+0x10]
        ///48 85 c0                test   rax,rax
        ///74 30                   je     4e &lt;exit&gt;
        ///48 8b 80 48 04 00 00    mov    rax,QWORD PTR [rax+0x448]
        ///48 85 c0                test   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DSRSetThrowState {
            get {
                return ResourceManager.GetString("DSRSetThrowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 3b 98 08 e5 01 00    cmp    rbx,QWORD PTR [rax+0x1e508]
        ///75 20                   jne    31 &lt;skip&gt;
        ///48 85 f6                test   rsi,rsi
        ///74 12                   je     28 &lt;count_hit&gt;
        ///48 3b b0 08 e5 01 00    cmp    rsi,QWORD PTR [rax+0x1e508]
        ///74 12                   je     31 &lt;skip&gt;
        ///81 7e 60 40 42 0f 00    cmp    DWORD PTR [rsi+0x60],0xf4240
        ///74 09                   je     31 &lt;skip&gt;
        ///
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingAuxDamageAttacker {
            get {
                return ResourceManager.GetString("EldenRingAuxDamageAttacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 09 83 b8 00 00 00       or     DWORD PTR [rbx+0xb8],eax
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # d &lt;_main+0xd&gt;
        ///74 06                   je     15 &lt;skip&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 15 &lt;skip&gt;
        ///000000000015 &lt;skip&gt;:
        ///e9 00 00 00 00          jmp    1a &lt;skip+0x5&gt;.
        /// </summary>
        internal static string EldenRingAuxProc {
            get {
                return ResourceManager.GetString("EldenRingAuxProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 7 &lt;_main+0x7&gt;
        ///48 85 c0                test   rax,rax
        ///74 28                   je     34 &lt;dead&gt;
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 85 c0                test   rax,rax
        ///74 1c                   je     34 &lt;dead&gt;
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///48 85 c0                test   rax,rax
        ///74 10                   je     34 &lt;dead&gt;
        ///48 8b 00                mov    rax,QWORD PTR [rax]
        ///48 85 c0          [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingCheckPlayerDead {
            get {
                return ResourceManager.GetString("EldenRingCheckPlayerDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 7 &lt;_main+0x7&gt;
        ///74 0f                   je     18 &lt;original&gt;
        ///80 b9 56 01 00 00 20    cmp    BYTE PTR [rcx+0x156],0x20
        ///75 06                   jne    18 &lt;original&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 18 &lt;original&gt;
        ///000000000018 &lt;original&gt;:
        ///0f b6 81 59 02 00 00    movzx  eax,BYTE PTR [rcx+0x259]
        ///e9 00 00 00 00          jmp    24 &lt;original+0xc&gt;.
        /// </summary>
        internal static string EldenRingCheckStateInfo {
            get {
                return ResourceManager.GetString("EldenRingCheckStateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53                      push   rbx
        ///48 83 ec 30             sub    rsp,0x30
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # d &lt;_main+0xd&gt;
        ///48 85 c0                test   rax,rax
        ///74 31                   je     43 &lt;exit&gt;
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 85 c0                test   rax,rax
        ///74 25                   je     43 &lt;exit&gt;
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///48 85 c0                test   rax,rax [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingClearThrowState {
            get {
                return ResourceManager.GetString("EldenRingClearThrowState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f3 0f 10 6d a0          movss  xmm5,DWORD PTR [rbp-0x60]
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # c &lt;_main+0xc&gt;
        ///74 36                   je     44 &lt;done&gt;
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 15 &lt;_main+0x15&gt;
        ///74 2d                   je     44 &lt;done&gt;
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 1e &lt;_main+0x1e&gt;
        ///74 24                   je     44 &lt;done&gt;
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 27 &lt;_main+0x27&gt;
        ///45 0f 57 f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingDeflectTear {
            get {
                return ResourceManager.GetString("EldenRingDeflectTear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///e8 00 00 00 00          call   6 &lt;_main+0x6&gt;
        ///58                      pop    rax
        ///74 5e                   je     67 &lt;skip&gt;
        ///52                      push   rdx
        ///03 91 38 01 00 00       add    edx,DWORD PTR [rcx+0x138]
        ///85 d2                   test   edx,edx
        ///7f 52                   jg     66 &lt;skip_lookup&gt;
        ///51                      push   rcx
        ///41 50                   push   r8
        ///4c 8b 05 00 00 00 00    mov    r8,QWORD PTR [rip+0x0]        # 1e &lt;_main+0x1e&gt;
        ///49 8b 90 08 e5 01  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingEnvKilling {
            get {
                return ResourceManager.GetString("EldenRingEnvKilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 5c 24 08          mov    QWORD PTR [rsp+0x8],rbx
        ///50                      push   rax
        ///53                      push   rbx
        ///57                      push   rdi
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///89 f8                   mov    eax,edi
        ///6b c0 05                imul   eax,eax,0x5
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # 1a &lt;_main+0x1a&gt;
        ///48 01 c3                add    rbx,rax
        ///89 13                   mov    DWORD PTR [rbx],edx
        ///44 88 43 04            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingEventLog {
            get {
                return ResourceManager.GetString("EldenRingEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BossName,DeathFlag
        ///Abductor Virgins,16000860
        ///&quot;Adan, Thief of Fire&quot;,1038410800
        ///&quot;Alecto, Black Knife Ringleader&quot;,1033420800
        ///Ancestor Spirit,12080800
        ///Ancient Dragon Lansseax,1041520800
        ///Ancient Hero of Zamor (Sainted Hero&apos;s Grave),30080800
        ///Ancient Hero of Zamor (Giant-Conquering Hero&apos;s Grave),30170800
        ///Ancient Hero of Zamor (Weeping Evergaol),1042330800
        ///&quot;Astel, Naturalborn of the Void&quot;,12040800
        ///&quot;Astel, Stars of Darkness&quot;,32110800
        ///Battlemage Hugues,1049390850
        ///Beastman of Farum Azula,31030800
        ///Beastman [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingEvents {
            get {
                return ResourceManager.GetString("EldenRingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 44 24 30 01          mov    BYTE PTR [rsp+0x30],0x1
        ///50                      push   rax
        ///51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///48 8b 81 08 e5 01 00    mov    rax,QWORD PTR [rcx+0x1e508]
        ///48 8b 80 90 01 00 00    mov    rax,QWORD PTR [rax+0x190]
        ///4c 3b 38                cmp    r15,QWORD PTR [rax]
        ///74 30                   je     51 &lt;validate_fall&gt;
        ///48 8b 80 e8 00 00 00    mov    rax,QWORD PTR [rax+0xe8]
        ///48 8b 40 10             mov [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingFallDamage {
            get {
                return ResourceManager.GetString("EldenRingFallDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bf 01 00 00 00          mov    edi,0x1
        ///50                      push   rax
        ///e8 00 00 00 00          call   b &lt;_main+0xb&gt;
        ///74 54                   je     61 &lt;early_exit&gt;
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 14 &lt;_main+0x14&gt;
        ///48 85 c0                test   rax,rax
        ///74 48                   je     61 &lt;early_exit&gt;
        ///48 8b 80 08 e5 01 00    mov    rax,QWORD PTR [rax+0x1e508]
        ///48 85 c0                test   rax,rax
        ///74 3c                   je     61 &lt;early_exit&gt;
        ///48 8b 80 90 01 00 00    m [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingHandleThrow {
            get {
                return ResourceManager.GetString("EldenRingHandleThrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 7 &lt;_main+0x7&gt;
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # e &lt;_main+0xe&gt;
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 15 &lt;_main+0x15&gt;
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 1c &lt;_main+0x1c&gt;
        ///48 89 5c 24 08          mov    QWORD PTR [rsp+0x8],rbx
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # 28 &lt;_main+0x28&gt;
        ///0f 84 eb 01 00 00       je     219 &lt;skip_all&gt;
        ///50            [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingHit {
            get {
                return ResourceManager.GetString("EldenRingHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e8 00 00 00 00          call   5 &lt;_main+0x5&gt;
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # c &lt;_main+0xc&gt;
        ///0f 84 82 00 00 00       je     94 &lt;exit_no_pop&gt;
        ///51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # 1a &lt;_main+0x1a&gt;
        ///48 85 c9                test   rcx,rcx
        ///74 74                   je     93 &lt;exit&gt;
        ///48 8b 89 08 e5 01 00    mov    rcx,QWORD PTR [rcx+0x1e508]
        ///48 85 c9                test   rcx,rcx
        ///74 68                   je     93 &lt;exit&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingKillBox {
            get {
                return ResourceManager.GetString("EldenRingKillBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///e8 00 00 00 00          call   6 &lt;_main+0x6&gt;
        ///74 16                   je     1e &lt;exit&gt;
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # f &lt;_main+0xf&gt;
        ///48 3b 88 08 e5 01 00    cmp    rcx,QWORD PTR [rax+0x1e508]
        ///75 06                   jne    1e &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 1e &lt;exit&gt;
        ///
        ///00000000001e &lt;exit&gt;:
        ///58                      pop    rax
        ///48 89 cb                mov    rbx,rcx
        ///48 8b 89 90 01 00 00    mov    rcx,Q [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingKillChr {
            get {
                return ResourceManager.GetString("EldenRingKillChr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ba 05 00 00 00          mov    edx,0x5
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # c &lt;_main+0xc&gt;
        ///e9 00 00 00 00          jmp    11 &lt;_main+0x11&gt;.
        /// </summary>
        internal static string EldenRingRunStart {
            get {
                return ResourceManager.GetString("EldenRingRunStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53                      push   rbx
        ///50                      push   rax
        ///41 50                   push   r8
        ///e8 00 00 00 00          call   9 &lt;_main+0x9&gt;
        ///0f 84 ed 00 00 00       je     fc &lt;skip&gt;
        ///48 8b 1d 00 00 00 00    mov    rbx,QWORD PTR [rip+0x0]        # 16 &lt;_main+0x16&gt;
        ///48 85 db                test   rbx,rbx
        ///0f 84 dd 00 00 00       je     fc &lt;skip&gt;
        ///48 8b 9b 08 e5 01 00    mov    rbx,QWORD PTR [rbx+0x1e508]
        ///48 85 db                test   rbx,rbx
        ///0f 84 cd 00 00 00       je     fc &lt;skip&gt;
        ///48 8b 83 90  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingSpEffectTickDamage {
            get {
                return ResourceManager.GetString("EldenRingSpEffectTickDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 7 &lt;_main+0x7&gt;
        ///74 11                   je     1a &lt;original&gt;
        ///84 c0                   test   al,al
        ///74 06                   je     13 &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 13 &lt;exit&gt;
        ///000000000013 &lt;exit&gt;:
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 1a &lt;original&gt;
        ///00000000001a &lt;original&gt;:
        ///45 0f 57 c9             xorps  xmm9,xmm9
        ///84 c0                   test   al,al
        ///e9 00 00 00 00          jmp     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EldenRingStaggerEndure {
            get {
                return ResourceManager.GetString("EldenRingStaggerEndure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///48 a1 00 00 00 00 00    movabs rax,ds:0x0
        ///00 00 00
        ///48 8b 80 d0 00 00 00    mov    rax,QWORD PTR [rax+0xd0]
        ///48 8b 80 f8 00 00 00    mov    rax,QWORD PTR [rax+0xf8]
        ///48 8b 80 f0 00 00 00    mov    rax,QWORD PTR [rax+0xf0]
        ///f3 0f 10 80 98 37 00    movss  xmm0,DWORD PTR [rax+0x3798]
        ///00
        ///58                      pop    rax
        ///0f 29 44 24 20          movaps XMMWORD PTR [rsp+0x20],xmm0
        ///e9 00 00 00 00          jmp    33 &lt;_main+0x33&gt;.
        /// </summary>
        internal static string ScholarBabyJump {
            get {
                return ResourceManager.GetString("ScholarBabyJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 7 &lt;_main+0x7&gt;
        ///48 85 c0                test   rax,rax
        ///74 14                   je     20 &lt;dead&gt;
        ///48 8b 80 d0 00 00 00    mov    rax,QWORD PTR [rax+0xd0]
        ///48 85 c0                test   rax,rax
        ///74 08                   je     20 &lt;dead&gt;
        ///83 b8 68 01 00 00 00    cmp    DWORD PTR [rax+0x168],0x0
        ///c3                      ret
        ///
        ///000000000020 &lt;dead&gt;:
        ///31 c0                   xor    eax,eax
        ///c3                      ret.
        /// </summary>
        internal static string ScholarCheckPlayerDead {
            get {
                return ResourceManager.GetString("ScholarCheckPlayerDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 84 2a 20 01 00 00    and    BYTE PTR [rdx+rbp*1+0x120],al
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # e &lt;_main+0xe&gt;
        ///74 33                   je     43 &lt;early_exit&gt;
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 18 &lt;_main+0x18&gt;
        ///48 85 c0                test   rax,rax
        ///74 25                   je     42 &lt;exit&gt;
        ///48 8b 80 d0 00 00 00    mov    rax,QWORD PTR [rax+0xd0]
        ///48 85 c0                test   rax,rax
        ///74 19                   je   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarClearWetPoisonBit {
            get {
                return ResourceManager.GetString("ScholarClearWetPoisonBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4c 8b 01                mov    r8,QWORD PTR [rcx]
        ///48 63 c2                movsxd rax,edx
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # d &lt;_main+0xd&gt;
        ///74 14                   je     23 &lt;check_wet&gt;
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 16 &lt;_main+0x16&gt;
        ///83 fa 02                cmp    edx,0x2
        ///74 23                   je     3e &lt;skip&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 21 &lt;_main+0x21&gt;
        ///eb 1b                   jmp    3e &lt;skip&gt;
        ///
        ///000000000023  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarCountAuxHit {
            get {
                return ResourceManager.GetString("ScholarCountAuxHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 81 ec 20 02 00 00    sub    rsp,0x220
        ///83 3d 00 00 00 00 00    cmp    DWORD PTR [rip+0x0],0x0        # e &lt;_main+0xe&gt;
        ///75 11                   jne    21 &lt;skip&gt;
        ///c7 41 28 07 00 00 00    mov    DWORD PTR [rcx+0x28],0x7
        ///c7 05 00 00 00 00 01    mov    DWORD PTR [rip+0x0],0x1        # 21 &lt;skip&gt;
        ///00 00 00
        ///000000000021 &lt;skip&gt;:
        ///e9 00 00 00 00          jmp    26 &lt;skip+0x5&gt;.
        /// </summary>
        internal static string ScholarCreditSkip {
            get {
                return ResourceManager.GetString("ScholarCreditSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///53                      push   rbx
        ///57                      push   rdi
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # 9 &lt;_main+0x9&gt;
        ///89 f8                   mov    eax,edi
        ///6b c0 05                imul   eax,eax,0x5
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # 15 &lt;_main+0x15&gt;
        ///48 01 c3                add    rbx,rax
        ///89 13                   mov    DWORD PTR [rbx],edx
        ///44 88 43 04             mov    BYTE PTR [rbx+0x4],r8b
        ///ff c7                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarEventLog {
            get {
                return ResourceManager.GetString("ScholarEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b 8b 68 01 00 00       mov    ecx,DWORD PTR [rbx+0x168]
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # e &lt;_main+0xe&gt;
        ///48 39 98 d0 00 00 00    cmp    QWORD PTR [rax+0xd0],rbx
        ///75 0e                   jne    25 &lt;exit&gt;
        ///89 c8                   mov    eax,ecx
        ///29 f0                   sub    eax,esi
        ///85 c0                   test   eax,eax
        ///7f 06                   jg     25 &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 25 &lt;exit&gt;
        ///
        ///00000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarGeneralApplyDamage {
            get {
                return ResourceManager.GetString("ScholarGeneralApplyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 81 b8 00 00 00    mov    rax,QWORD PTR [rcx+0xb8]
        ///83 b8 f0 05 00 00 00    cmp    DWORD PTR [rax+0x5f0],0x0
        ///75 21                   jne    31 &lt;yes&gt;
        ///83 b8 f8 05 00 00 00    cmp    DWORD PTR [rax+0x5f8],0x0
        ///75 18                   jne    31 &lt;yes&gt;
        ///83 b8 fc 05 00 00 00    cmp    DWORD PTR [rax+0x5fc],0x0
        ///75 0f                   jne    31 &lt;yes&gt;
        ///48 8b 81 d0 00 00 00    mov    rax,QWORD PTR [rcx+0xd0]
        ///f6 00 02                test   BYTE PTR [rax],0x2
        ///75 03                   jne    31 &lt;yes&gt;
        ///30 c0     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarHasIframes {
            get {
                return ResourceManager.GetString("ScholarHasIframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 7 &lt;_main+0x7&gt;
        ///50                      push   rax
        ///e8 00 00 00 00          call   d &lt;_main+0xd&gt;
        ///0f 84 c6 00 00 00       je     d9 &lt;exit&gt;
        ///81 7c 24 54 e6 50 f5    cmp    DWORD PTR [rsp+0x54],0x5f550e6
        ///05 
        ///0f 84 b8 00 00 00       je     d9 &lt;exit&gt;
        ///53                      push   rbx
        ///48 8b 1d 00 00 00 00    mov    rbx,QWORD PTR [rip+0x0]        # 29 &lt;_main+0x29&gt;
        ///48 8b 9b d0 00 00 00    mov    rbx,QWORD PTR [rbx+0xd0]
        ///48 3b 59 08             cm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarHit {
            get {
                return ResourceManager.GetString("ScholarHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 87 60 13 00 00    mov    QWORD PTR [rdi+0x1360],rax
        ///c7 05 00 00 00 00 03    mov    DWORD PTR [rip+0x0],0x3        # 11 &lt;_main+0x11&gt;
        ///00 00 00
        ///e9 00 00 00 00          jmp    16 &lt;_main+0x16&gt;.
        /// </summary>
        internal static string ScholarIgtLoadGame {
            get {
                return ResourceManager.GetString("ScholarIgtLoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 89 83 60 13 00 00    mov    QWORD PTR [rbx+0x1360],rax
        ///c7 05 00 00 00 00 01    mov    DWORD PTR [rip+0x0],0x1        # 11 &lt;_main+0x11&gt;
        ///00 00 00
        ///e9 00 00 00 00          jmp    16 &lt;_main+0x16&gt;.
        /// </summary>
        internal static string ScholarIgtNewGame {
            get {
                return ResourceManager.GetString("ScholarIgtNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 83 f8 06                cmp    eax,0x6
        ///75 0a                   jne    f &lt;exit&gt;
        ///c7 05 00 00 00 00 02    mov    DWORD PTR [rip+0x0],0x2        # f &lt;exit&gt;
        ///00 00 00 
        ///
        ///00000000000f &lt;exit&gt;:
        ///24 fd                   and    al,0xfd
        ///c7 86 ac 24 00 00 1f    mov    DWORD PTR [rsi+0x24ac],0x1f
        ///00 00 00 
        ///e9 00 00 00 00          jmp    20 &lt;exit+0x11&gt;.
        /// </summary>
        internal static string ScholarIgtStop {
            get {
                return ResourceManager.GetString("ScholarIgtStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4c 8b 01                mov    r8,QWORD PTR [rcx]
        ///51                      push   rcx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # b &lt;_main+0xb&gt;
        ///4c 3b 81 d0 00 00 00    cmp    r8,QWORD PTR [rcx+0xd0]
        ///75 0a                   jne    1e &lt;exit&gt;
        ///85 d2                   test   edx,edx
        ///75 06                   jne    1e &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 1e &lt;exit&gt;
        ///00000000001e &lt;exit&gt;:
        ///59                      pop    rcx
        ///89 54 24 10             mov    DWORD  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarKillBox {
            get {
                return ResourceManager.GetString("ScholarKillBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 88 4e 17             mov    BYTE PTR [r14+0x17],cl
        ///48 8b 47 08             mov    rax,QWORD PTR [rdi+0x8]
        ///80 f9 02                cmp    cl,0x2
        ///75 2d                   jne    3a &lt;early_exit&gt;
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 15 &lt;_main+0x15&gt;
        ///48 85 c0                test   rax,rax
        ///74 1f                   je     39 &lt;exit&gt;
        ///48 8b 80 d0 00 00 00    mov    rax,QWORD PTR [rax+0xd0]
        ///48 85 c0                test   rax,rax
        ///74 13              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ScholarStaggerCheck {
            get {
                return ResourceManager.GetString("ScholarStaggerCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 7 &lt;_main+0x7&gt;
        ///50                      push   rax
        ///53                      push   rbx
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 10 &lt;_main+0x10&gt;
        ///48 85 c0                test   rax,rax
        ///74 4e                   je     63 &lt;skip&gt;
        ///48 8b 80 88 00 00 00    mov    rax,QWORD PTR [rax+0x88]
        ///48 85 c0                test   rax,rax
        ///74 42                   je     63 &lt;skip&gt;
        ///48 8b 80 f8 1f 00 00    mov    rax,QWORD PTR [rax+0x1ff8]
        ///4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKApplyHealthDelta {
            get {
                return ResourceManager.GetString("SKApplyHealthDelta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///51                      push   rcx
        ///52                      push   rdx
        ///48 8b 0d 00 00 00 00    mov    rcx,QWORD PTR [rip+0x0]        # a &lt;_main+0xa&gt;
        ///48 85 c9                test   rcx,rcx
        ///0f 84 aa 00 00 00       je     bd &lt;exit&gt;
        ///48 8b 89 88 00 00 00    mov    rcx,QWORD PTR [rcx+0x88]
        ///48 85 c9                test   rcx,rcx
        ///0f 84 9a 00 00 00       je     bd &lt;exit&gt;
        ///48 39 c1                cmp    rcx,rax
        ///0f 85 91 00 00 00       jne    bd &lt;exit&gt;
        ///48 8b 89 d0 11 00 00   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKApplySpEffectDamage {
            get {
                return ResourceManager.GetString("SKApplySpEffectDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d3 e0                   shl    eax,cl
        ///41 09 41 4c             or     DWORD PTR [r9+0x4c],eax
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # d &lt;_main+0xd&gt;
        ///74 06                   je     15 &lt;skip&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 15 &lt;skip&gt;
        ///
        ///000000000015 &lt;skip&gt;:
        ///e9 00 00 00 00          jmp    1a &lt;skip+0x5&gt;.
        /// </summary>
        internal static string SKAuxProc {
            get {
                return ResourceManager.GetString("SKAuxProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 49 8b 5d 00             mov    rbx,QWORD PTR [r13+0x0]
        ///4c 89 e9                mov    rcx,r13
        ///50                      push   rax
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # f &lt;_main+0xf&gt;
        ///48 85 c0                test   rax,rax
        ///74 1a                   je     2e &lt;skip&gt;
        ///48 8b 80 88 00 00 00    mov    rax,QWORD PTR [rax+0x88]
        ///4c 39 f0                cmp    rax,r14
        ///75 0e                   jne    2e &lt;skip&gt;
        ///48 39 c8                cmp    rax,rcx
        ///74 09                   je     2e &lt;skip&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKCheckAuxAttacker {
            get {
                return ResourceManager.GetString("SKCheckAuxAttacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 05 00 00 00 00
        ///48 85 c0
        ///74 29
        ///48 8b 80 88 00 00 00
        ///48 85 c0
        ///74 1d
        ///48 8b 80 f8 1f 00 00
        ///48 85 c0
        ///74 11
        ///48 8b 40 18
        ///48 85 c0
        ///74 08
        ///83 b8 30 01 00 00 00
        ///c3
        ///31 c0
        ///c3.
        /// </summary>
        internal static string SKCheckPlayerDead {
            get {
                return ResourceManager.GetString("SKCheckPlayerDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 48 8b 06                mov    rax,QWORD PTR [rsi]
        ///41 0f 28 c9             movaps xmm1,xmm9
        ///80 3d 00 00 00 00 01    cmp    BYTE PTR [rip+0x0],0x1        # e &lt;_main+0xe&gt;
        ///75 06                   jne    16 &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 16 &lt;exit&gt;
        ///
        ///000000000016 &lt;exit&gt;:
        ///e9 00 00 00 00          jmp    1b &lt;exit+0x5&gt;.
        /// </summary>
        internal static string SKDeferredFallCheck {
            get {
                return ResourceManager.GetString("SKDeferredFallCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c7 45 c0 ff ff ff ff    mov    DWORD PTR [rbp-0x40],0xffffffff
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # e &lt;_main+0xe&gt;
        ///74 10                   je     20 &lt;exit&gt;
        ///41 80 bf c7 01 00 00    cmp    BYTE PTR [r15+0x1c7],0x0
        ///00
        ///75 06                   jne    20 &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 20 &lt;exit&gt;
        ///000000000020 &lt;exit&gt;:
        ///e9 00 00 00 00          jmp    25 &lt;exit+0x5&gt;.
        /// </summary>
        internal static string SKDeflectCheck {
            get {
                return ResourceManager.GetString("SKDeflectCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///53                      push   rbx
        ///57                      push   rdi
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR [rip+0x0]        # 9 &lt;_main+0x9&gt;
        ///89 f8                   mov    eax,edi
        ///6b c0 05                imul   eax,eax,0x5
        ///48 8d 1d 00 00 00 00    lea    rbx,[rip+0x0]        # 15 &lt;_main+0x15&gt;
        ///48 01 c3                add    rbx,rax
        ///89 13                   mov    DWORD PTR [rbx],edx
        ///44 88 43 04             mov    BYTE PTR [rbx+0x4],r8b
        ///ff c7                   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKEventLog {
            get {
                return ResourceManager.GetString("SKEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BossName,DeathFlag
        ///Armored Warrior,12000400
        ///Ashina Elite - Jinsuke Saze,11110504
        ///Ashina Elite - Ujinari Mizuo,11110511
        ///Blazing Bull,11110440
        ///Chained Ogre (Castle),11110620
        ///Chained Ogre (Outskirts),11100310
        ///Demon of Hatred / Demon of Hatred (Gauntlet),11100900
        ///Divine Dragon,9310
        ///Fake Monk,9306
        ///Folding Screen Monkeys,9305
        ///General Kuranosuke Matsumoto,11110410
        ///General Naomori Kawarada,11100300
        ///General Tenzen Yamauchi,11100301
        ///Genichiro Ashina (Castle) / Genichiro Ashina (Gauntlet),11110800
        ///Genic [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKEvents {
            get {
                return ResourceManager.GetString("SKEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53                      push   rbx
        ///48 8b 1d 00 00 00 00    mov    rbx,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 85 db                test   rbx,rbx
        ///74 0f                   je     1c &lt;exit&gt;
        ///48 3b 83 88 00 00 00    cmp    rax,QWORD PTR [rbx+0x88]
        ///75 06                   jne    1c &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 1c &lt;exit&gt;
        ///
        ///00000000001c &lt;exit&gt;:
        ///5b                      pop    rbx
        ///48 8b 88 f8 1f 00 00    mov    rcx,QWORD PTR [rax+0x1ff8]
        ///e9 00 00 00 00          jm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKFadeFall {
            get {
                return ResourceManager.GetString("SKFadeFall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53                      push   rbx
        ///48 8b 1d 00 00 00 00    mov    rbx,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 85 db                test   rbx,rbx
        ///74 0f                   je     1c &lt;skip&gt;
        ///48 3b 83 88 00 00 00    cmp    rax,QWORD PTR [rbx+0x88]
        ///75 06                   jne    1c &lt;skip&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 1c &lt;skip&gt;
        ///
        ///00000000001c &lt;skip&gt;:
        ///5b                      pop    rbx
        ///48 8b 88 f8 1f 00 00    mov    rcx,QWORD PTR [rax+0x1ff8]
        ///e9 00 00 00 00          jm [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKFadeFallHeight {
            get {
                return ResourceManager.GetString("SKFadeFallHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 7 &lt;_main+0x7&gt;
        ///48 89 44 24 50          mov    QWORD PTR [rsp+0x50],rax
        ///50                      push   rax
        ///e8 00 00 00 00          call   12 &lt;_main+0x12&gt;
        ///0f 84 a5 01 00 00       je     1bd &lt;skip_count&gt;
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 1f &lt;_main+0x1f&gt;
        ///48 8b 80 88 00 00 00    mov    rax,QWORD PTR [rax+0x88]
        ///48 39 d0                cmp    rax,rdx
        ///0f 84 8e 01 00 00       je     1bd &lt;skip_count&gt;
        ///48 8b 80 f8 1f 00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKHit {
            get {
                return ResourceManager.GetString("SKHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///e8 00 00 00 00          call   6 &lt;_main+0x6&gt;
        ///74 28                   je     30 &lt;exit&gt;
        ///57                      push   rdi
        ///48 8b 05 00 00 00 00    mov    rax,QWORD PTR [rip+0x0]        # 10 &lt;_main+0x10&gt;
        ///48 8b 80 88 00 00 00    mov    rax,QWORD PTR [rax+0x88]
        ///48 8b 3f                mov    rdi,QWORD PTR [rdi]
        ///48 3b 47 28             cmp    rax,QWORD PTR [rdi+0x28]
        ///75 0f                   jne    2f &lt;skip&gt;
        ///41 81 fe 64 0b 00 00    cmp    r14d,0xb64
        ///75 06                [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKHkbFireEvent {
            get {
                return ResourceManager.GetString("SKHkbFireEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 53                      push   rbx
        ///48 8b 1d 00 00 00 00    mov    rbx,QWORD PTR [rip+0x0]        # 8 &lt;_main+0x8&gt;
        ///48 85 db                test   rbx,rbx
        ///74 0f                   je     1c &lt;exit&gt;
        ///48 3b 83 88 00 00 00    cmp    rax,QWORD PTR [rbx+0x88]
        ///75 06                   jne    1c &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 1c &lt;exit&gt;
        ///00000000001c &lt;exit&gt;:
        ///5b                      pop    rbx
        ///48 8b 88 f8 1f 00 00    mov    rcx,QWORD PTR [rax+0x1ff8]
        ///e9 00 00 00 00          jmp  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKLethalFall {
            get {
                return ResourceManager.GetString("SKLethalFall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   rax
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 8 &lt;_main+0x8&gt;
        ///0f 84 a9 00 00 00       je     b7 &lt;commit_skip&gt;
        ///41 83 be e0 01 00 00    cmp    DWORD PTR [r14+0x1e0],0x0
        ///00 
        ///0f 8f 85 00 00 00       jg     a1 &lt;commit_hit&gt;
        ///41 80 be c7 01 00 00    cmp    BYTE PTR [r14+0x1c7],0x0
        ///00 
        ///0f 85 86 00 00 00       jne    b0 &lt;commit_discard&gt;
        ///41 0f b6 46 24          movzx  eax,BYTE PTR [r14+0x24]
        ///83 f8 0b                cmp    eax,0xb
        ///75 27                   jne  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKPostHit {
            get {
                return ResourceManager.GetString("SKPostHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 41 b0 01                mov    r8b,0x1
        ///31 d2                   xor    edx,edx
        ///c6 05 00 00 00 00 01    mov    BYTE PTR [rip+0x0],0x1        # c &lt;_main+0xc&gt;
        ///e9 00 00 00 00          jmp    11 &lt;_main+0x11&gt;.
        /// </summary>
        internal static string SKRunStart {
            get {
                return ResourceManager.GetString("SKRunStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f3 0f 10 a5 10 02 00    movss  xmm4,DWORD PTR [rbp+0x210]
        ///00 
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # f &lt;_main+0xf&gt;
        ///74 3c                   je     4d &lt;exit&gt;
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 18 &lt;_main+0x18&gt;
        ///83 7d 6c 00             cmp    DWORD PTR [rbp+0x6c],0x0
        ///75 29                   jne    47 &lt;count_hit&gt;
        ///51                      push   rcx
        ///52                      push   rdx
        ///50                      push   rax
        ///ba c9 26 02 00          mov    edx,0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKSakuraDance {
            get {
                return ResourceManager.GetString("SKSakuraDance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80 3d 00 00 00 00 00    cmp    BYTE PTR [rip+0x0],0x0        # 7 &lt;_main+0x7&gt;
        ///74 1a                   je     23 &lt;original&gt;
        ///85 c0                   test   eax,eax
        ///74 0f                   je     1c &lt;exit&gt;
        ///80 bf c7 01 00 00 00    cmp    BYTE PTR [rdi+0x1c7],0x0
        ///75 06                   jne    1c &lt;exit&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR [rip+0x0]        # 1c &lt;exit&gt;
        ///
        ///00000000001c &lt;exit&gt;:
        ///c6 05 00 00 00 00 00    mov    BYTE PTR [rip+0x0],0x0        # 23 &lt;original&gt;
        ///
        ///000000000023 &lt;original&gt;:
        ///45 0f  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SKStaggerIgnoreCheck {
            get {
                return ResourceManager.GetString("SKStaggerIgnoreCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0f 51 c0                sqrtps xmm0,xmm0
        ///50                      push   eax
        ///a1 00 00 00 00          mov    eax,ds:0x0
        ///8b 40 74                mov    eax,DWORD PTR [eax+0x74]
        ///8b 80 94 04 00 00       mov    eax,DWORD PTR [eax+0x494]
        ///f3 0f 10 80 e8 00 00    movss  xmm0,DWORD PTR [eax+0xe8]
        ///00
        ///58                      pop    eax
        ///0f 29 45 b0             movaps XMMWORD PTR [ebp-0x50],xmm0
        ///e9 fc ff ff ff          jmp    20 &lt;_main+0x20&gt;.
        /// </summary>
        internal static string VanillaBabyJump {
            get {
                return ResourceManager.GetString("VanillaBabyJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a1 00 00 00 00          mov    eax,ds:0x0
        ///85 c0                   test   eax,eax
        ///74 0f                   je     18 &lt;dead&gt;
        ///8b 40 74                mov    eax,DWORD PTR [eax+0x74]
        ///85 c0                   test   eax,eax
        ///74 08                   je     18 &lt;dead&gt;
        ///83 b8 fc 00 00 00 00    cmp    DWORD PTR [eax+0xfc],0x0
        ///c3                      ret
        ///
        ///0018 &lt;dead&gt;:
        ///31 c0                   xor    eax,eax
        ///c3                      ret.
        /// </summary>
        internal static string VanillaCheckPlayerDead {
            get {
                return ResourceManager.GetString("VanillaCheckPlayerDead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8d 94 1a 10 01 00 00    lea    edx,[edx+ebx*1+0x110]
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR ds:0x0,0x0
        ///74 28                   je     38 &lt;early_exit&gt;
        ///50                      push   eax
        ///a1 00 00 00 00          mov    eax,ds:0x0
        ///85 c0                   test   eax,eax
        ///74 1d                   je     37 &lt;exit&gt;
        ///8b 40 74                mov    eax,DWORD PTR [eax+0x74]
        ///85 c0                   test   eax,eax
        ///74 16                   je     37 &lt;exit&gt;
        ///83 ff 0b                cmp    edi,0xb
        ///75 11              [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VanillaClearWetPoisonBit {
            get {
                return ResourceManager.GetString("VanillaClearWetPoisonBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f3 0f 10 55 0c          movss  xmm2,DWORD PTR [ebp+0xc]
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR ds:0x0,0x0
        ///74 14                   je     22 &lt;check_wet&gt;
        ///c6 05 00 00 00 00 00    mov    BYTE PTR ds:0x0,0x0
        ///83 f8 02                cmp    eax,0x2
        ///74 23                   je     3d &lt;skip&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR ds:0x0
        ///eb 1b                   jmp    3d &lt;skip&gt;
        ///
        ///0022 &lt;check_wet&gt;:
        ///80 3d 00 00 00 00 00    cmp    BYTE PTR ds:0x0,0x0
        ///74 12                   je     3d &lt;skip&gt;
        ///83 f8 00         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VanillaCountAuxHit {
            get {
                return ResourceManager.GetString("VanillaCountAuxHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81 ec fc 01 00 00       sub    esp,0x1fc
        ///83 3d 00 00 00 00 00    cmp    DWORD PTR ds:0x0,0x0
        ///75 11                   jne    20 &lt;skip&gt;
        ///c7 41 14 07 00 00 00    mov    DWORD PTR [ecx+0x14],0x7
        ///c7 05 00 00 00 00 01    mov    DWORD PTR ds:0x0,0x1
        ///00 00 00
        ///0020 &lt;skip&gt;:
        ///e9 fc ff ff ff          jmp    21 &lt;skip+0x1&gt;.
        /// </summary>
        internal static string VanillaCreditSkip {
            get {
                return ResourceManager.GetString("VanillaCreditSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50                      push   eax
        ///53                      push   ebx
        ///57                      push   edi
        ///8b 3d 00 00 00 00       mov    edi,DWORD PTR ds:0x0
        ///89 f8                   mov    eax,edi
        ///6b c0 05                imul   eax,eax,0x5
        ///8d 1d 00 00 00 00       lea    ebx,ds:0x0
        ///01 c3                   add    ebx,eax
        ///89 33                   mov    DWORD PTR [ebx],esi
        ///8a 45 0c                mov    al,BYTE PTR [ebp+0xc]
        ///88 43 04                mov    BYTE PTR [ebx+0x4],al
        ///47                       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VanillaEventLog {
            get {
                return ResourceManager.GetString("VanillaEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b 86 fc 00 00 00       mov    eax,DWORD PTR [esi+0xfc]
        ///51                      push   ecx
        ///8b 0d 00 00 00 00       mov    ecx,DWORD PTR ds:0x0
        ///85 c9                   test   ecx,ecx
        ///74 13                   je     24 &lt;exit&gt;
        ///39 71 74                cmp    DWORD PTR [ecx+0x74],esi
        ///75 0e                   jne    24 &lt;exit&gt;
        ///89 c1                   mov    ecx,eax
        ///29 d1                   sub    ecx,edx
        ///85 c9                   test   ecx,ecx
        ///7f 06                   jg     24 &lt;exit&gt;
        ///ff 05 00 00 00 00       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VanillaGeneralApplyDamage {
            get {
                return ResourceManager.GetString("VanillaGeneralApplyDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b 81 94 00 00 00       mov    eax,DWORD PTR [ecx+0x94]
        ///83 b8 f0 05 00 00 00    cmp    DWORD PTR [eax+0x5f0],0x0
        ///75 20                   jne    2f &lt;yes&gt;
        ///83 b8 f8 05 00 00 00    cmp    DWORD PTR [eax+0x5f8],0x0
        ///75 17                   jne    2f &lt;yes&gt;
        ///83 b8 fc 05 00 00 00    cmp    DWORD PTR [eax+0x5fc],0x0
        ///75 0e                   jne    2f &lt;yes&gt;
        ///8b 81 a0 00 00 00       mov    eax,DWORD PTR [ecx+0xa0]
        ///f6 00 02                test   BYTE PTR [eax],0x2
        ///75 03                   jne    2f &lt;yes&gt;
        ///30 c0     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VanillaHasIframes {
            get {
                return ResourceManager.GetString("VanillaHasIframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c6 05 00 00 00 00 00    mov    BYTE PTR ds:0x0,0x0
        ///50                      push   eax
        ///e8 fc ff ff ff          call   9 &lt;_main+0x9&gt;
        ///0f 84 d8 00 00 00       je     eb &lt;exit&gt;
        ///81 bd f4 fd ff ff e6    cmp    DWORD PTR [ebp-0x20c],0x5f550e6
        ///50 f5 05 
        ///0f 84 c8 00 00 00       je     eb &lt;exit&gt;
        ///53                      push   ebx
        ///8b 1d 00 00 00 00       mov    ebx,DWORD PTR ds:0x0
        ///8b 5b 74                mov    ebx,DWORD PTR [ebx+0x74]
        ///3b 59 10                cmp    ebx,DWORD PTR [ecx+0x10]
        ///0f 85 b4 00 00 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VanillaHit {
            get {
                return ResourceManager.GetString("VanillaHit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 89 8f 60 13 00 00       mov    DWORD PTR [edi+0x1360],ecx
        ///c7 05 00 00 00 00 03    mov    DWORD PTR ds:0x0,0x3
        ///00 00 00 
        ///e9 fc ff ff ff          jmp    11 &lt;_main+0x11&gt;.
        /// </summary>
        internal static string VanillaIgtLoadGame {
            get {
                return ResourceManager.GetString("VanillaIgtLoadGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 89 8b 60 13 00 00       mov    DWORD PTR [ebx+0x1360],ecx
        ///c7 05 00 00 00 00 01    mov    DWORD PTR ds:0x0,0x1
        ///00 00 00 
        ///e9 fc ff ff ff          jmp    11 &lt;_main+0x11&gt;.
        /// </summary>
        internal static string VanillaIgtNewGame {
            get {
                return ResourceManager.GetString("VanillaIgtNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3c 06                   cmp    al,0x6
        ///75 0a                   jne    e &lt;exit&gt;
        ///c7 05 00 00 00 00 02    mov    DWORD PTR ds:0x0,0x2
        ///00 00 00 
        ///
        ///000e &lt;exit&gt;:
        ///24 fd                   and    al,0xfd
        ///0c 01                   or     al,0x1
        ///88 86 f1 0d 00 00       mov    BYTE PTR [esi+0xdf1],al
        ///e9 fc ff ff ff          jmp    19 &lt;exit+0xb&gt;.
        /// </summary>
        internal static string VanillaIgtStop {
            get {
                return ResourceManager.GetString("VanillaIgtStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8b 01                   mov    eax,DWORD PTR [ecx]
        ///8b 4d 08                mov    ecx,DWORD PTR [ebp+0x8]
        ///57                      push   edi
        ///8b 15 00 00 00 00       mov    edx,DWORD PTR ds:0x0
        ///85 d2                   test   edx,edx
        ///74 0f                   je     1f &lt;skip&gt;
        ///3b 42 74                cmp    eax,DWORD PTR [edx+0x74]
        ///75 0a                   jne    1f &lt;skip&gt;
        ///85 c9                   test   ecx,ecx
        ///75 06                   jne    1f &lt;skip&gt;
        ///ff 05 00 00 00 00       inc    DWORD PTR ds:0x0
        ///
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VanillaKillBox {
            get {
                return ResourceManager.GetString("VanillaKillBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 88 4f 17                mov    BYTE PTR [edi+0x17],cl
        ///8b 56 10                mov    edx,DWORD PTR [esi+0x10]
        ///80 f9 02                cmp    cl,0x2
        ///75 26                   jne    31 &lt;early_exit&gt;
        ///50                      push   eax
        ///a1 00 00 00 00          mov    eax,ds:0x0
        ///85 c0                   test   eax,eax
        ///74 1b                   je     30 &lt;exit&gt;
        ///8b 40 74                mov    eax,DWORD PTR [eax+0x74]
        ///85 c0                   test   eax,eax
        ///74 14                   je     30 &lt;exit&gt;
        ///3b 46 10      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string VanillaStaggerCheck {
            get {
                return ResourceManager.GetString("VanillaStaggerCheck", resourceCulture);
            }
        }
    }
}
